---
- name: install tomcat 10
  hosts: appserver
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for centos os"
      when: ansible_facts['distribution'] != 'centos'
    - name: update packages and install java
      ansible.builtin.yum:
        name: "{{ java_package_name }}"
        state: present
      become: yes
    - name: create tomcat group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
      become: yes
    - name: create tomcat user
      ansible.builtin.user:
        create_home: yes
        group: "{{ group }}"
        home: "{{ home_dir  }}"
        name: "{{ user }}"
        shell: "{{ user_shell }}"
        system: true
        state: present
      become: yes
    - name: download tomcat tar
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: /tmp/apache-tomcat-10.0.10.tar.gz