---
- name: install apache2 on ubuntu
  become: yes
  hosts: ubuntu
  tasks:
    - name: update and install apache2 on ubuntu
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: enable and start apache2 
      ansible.builtin.systemd_service:
        name: apache2
        enabled: true
        state: started


- name: install apache2 on centos
  become: yes
  hosts: RedHat
  tasks:
    - name: update and install httpd on centos
      ansible.builtin.dnf:
       name: httpd
       state: present
    - name: enable and start httpd
      ansible.builtin.systemd_service:
        name: httpd
        enabled: true
        state: started
      
