---
- name: install lamp stack
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for  os family"
      when: ansible_facts['os_family'] != 'RedHat'
    - name: update packages and install apache2
      ansible.builtin.yum:
        name: "{{ package }}"
        state: present
      notify:
        - enable and start apache
    - name: install php packages
      ansible.builtin.yum:
        name: "{{ php_packages }}"
        state: present
      notify:
        - restart apache
    - name: copy info.php
      copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart apache
  handlers:
    - name: enable and start apache
      service:
        name: "{{ package }}"
        enabled: yes
        state: started
    - name: restart apache
      service:
        name: "{{ package }}"
        state: restarted