---
- name: install tree
  hosts: all
  become: yes
  tasks:
    - name: tree install on ubuntu
      ansible.builtin.apt:
       name: tree
       update_cache: true
       state: present 


---
- name: install git
  hosts: all
  become: yes
  tasks:
    - name: git install on ubuntu
      ansible.builtin.apt:
       name: git
       update_cache: true
       state: present 
       